/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:d68e59b2-7ab0-462d-a31d-e084485750b1",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_ufo8uOVEF",
    "aws_user_pools_web_client_id": "4hiijk790fdbas4bcuu1nkn9i0",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://zettcr6lurajjf55rf3f34xezi.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
